name = "blog"
type = 'webpack'
account_id = '561f024b3ba2bbafa2a67ec9b911693c'
route = 'www.solberg.is/*'
zone_id = '1987b62adfbc2de205a723978c7d6ad3'
usage_model = ''
workers_dev = true
target_type = "webpack"
site = {bucket = "./build",entry-point = "workers-site"}
